[2024-11-24T04:34:43.658+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.inaccurate manual__2024-11-24T04:34:40.570415+00:00 [queued]>
[2024-11-24T04:34:43.664+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.inaccurate manual__2024-11-24T04:34:40.570415+00:00 [queued]>
[2024-11-24T04:34:43.664+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-24T04:34:43.671+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): inaccurate> on 2024-11-24 04:34:40.570415+00:00
[2024-11-24T04:34:43.674+0000] {standard_task_runner.py:60} INFO - Started process 194 to run task
[2024-11-24T04:34:43.676+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'inaccurate', 'manual__2024-11-24T04:34:40.570415+00:00', '--job-id', '5771', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp88t9ul_t']
[2024-11-24T04:34:43.678+0000] {standard_task_runner.py:88} INFO - Job 5771: Subtask inaccurate
[2024-11-24T04:34:43.709+0000] {task_command.py:423} INFO - Running <TaskInstance: first_dag.inaccurate manual__2024-11-24T04:34:40.570415+00:00 [running]> on host 70a89d0d486b
[2024-11-24T04:34:43.756+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T04:34:40.570415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T04:34:40.570415+00:00'
[2024-11-24T04:34:43.757+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-24T04:34:43.757+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-11-24T04:34:43.763+0000] {subprocess.py:86} INFO - Output:
[2024-11-24T04:34:43.764+0000] {subprocess.py:93} INFO - inaccurate
[2024-11-24T04:34:43.764+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-24T04:34:43.776+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=inaccurate, execution_date=20241124T043440, start_date=20241124T043443, end_date=20241124T043443
[2024-11-24T04:34:43.816+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-24T04:34:43.826+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
